### ISSUE TITLE
As an advisor, I need to sort lists of students...

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#101]
As an advisor, I need to sort lists of students so that I can order the students in whatever way works best for me, particularly so that I can find students who are most at risk very easily.

Requirements, ordered from highest to lowest priority:

1. Sort "My Students" list by status (more details on this at bottom)
2. Sort "My Students" list by last name
3. Sort "My Students" list by first name

User should be able to click column header to sort that column A-Z, and click again to sort Z-A. Note that for status sort, this would mean default seeing students with "lowest" status first.

Not sure if helpful but I've used [DataTables](https://datatables.net/) in the past to create dynamically sortable tables.

Details about sorting by status:
- Currently, I believe there is no aggregation of student's statuses in courses, only individual statuses per student-course combination. Some sort of aggregation will need to happen in order to sort by status
- I would like to sort by the AVERAGE status--add up all the statuses they have and divide by the number of statuses. The reason for this is that it will sort the students who are the most "at risk" to the top and will not matter how many classes a student is taking. Would like students with no courses or no statuses to bottom.

**Comment by jonespm** [comment]
This sounds like a good idea.

We could add Datatables, but I don't think that would make the requirements much easier here, though probably a package like [django-tables2 ](https://github.com/jieter/django-tables2)would be the way to go. Currently the entire names is in one column so to sort by last name we'd have to break those out to separate columns. 

I think we'd need a little more discussion about what the status sort algorithm and how it would work, we could do that after the other columns are sorted. 

I believe there is "Encourage/Explorer/Engage/No Data" but those have numbers behind them as well as the rank. 

Maybe there should also just be an option to hide students with no status?

**Comment by mfldavidson** [comment]
Good point about the names. If that's too hard, we can pause on that. The status is going to be the most important. I will point out though that in DM_STDNT where the name data comes from, the first and last names are separated.

The option to hide student with no status comes up in the filterable students issue #102 --you're right that is needed

Yes, I should have specified that the numbers behind the statuses per DM_ACAD_PERF are:
- 1 Green
- 2 Yellow
- 3 Red
- -4 is what I see showing up for situations where there's no data, although it says that one is "Not Applicable" and there are other negative values for missing, not happened yet, and bad value

It's not ideal that 1 is green and 3 is red instead of the other way around...

**Comment by zqian** [comment]
We have decided to use the [django-tables2](https://github.com/jieter/django-tables2) for this request.

Other things we looked at is [Django datatables view](https://pypi.org/project/django-datatables-view/) to work alongside with [datatables](https://datatables.net/)

**Comment by jonespm** [comment]
So I got this somewhat working with django-tables2 doing it the "easier way" by trying with the SingleTableView (provided by the library). However there's some complications with that.

- The current view actually joins across multiple tables (For the statues) and this isn't seeming to work yet with this method. 
- The logic to determine the status pictures is actually in the current view. This would probably have to be moved to the backend or a custom view created.

![image](https://user-images.githubusercontent.com/27447/59386893-cb978a00-8d35-11e9-97bc-37481960ab1e.png)

So I feel like this is going to be more work than I thought because of this multi-join query and logic in the view. We'll probably still get it to work but we'd have to write code for a custom table rather than using the View.

I think the easiest is going to be to go with [tablesorter](https://mottie.github.io/tablesorter/docs/), which is already used in Student Explorer on a few other views! I'd like to apply the [Bootstrap](https://mottie.github.io/tablesorter/docs/example-option-theme-bootstrap-v3.html) theme as otherwise the headers don't indicate they're sortable. 

![image](https://user-images.githubusercontent.com/27447/59389441-46fc3a00-8d3c-11e9-8793-9577747034c4.png)

Also I think for this pass we'll disable the Status field sorting and if that's desired we can look at enabling it. I think with table sorter it *should* be possible but would take a little more effort. We'll have to do that status calculation you suggest and store the value in the HTML as some data-* option then write a custom sort. I think this is possible but looking at how it's generated will probably take a few hours.

The current version also includes a field filter and you can search the status like "green", "red" etc which seems kind of neat.
![image](https://user-images.githubusercontent.com/27447/59389493-6c894380-8d3c-11e9-9ef6-6170e6f99b42.png)

Also the reason we didn't do client side will have the same problem, it will only sort the contents that are on the page. So we'll have to just load everything and do client side pagination, but this is quite possible. Hopefully nobody has thousands of students.

**Comment by mfldavidson** [comment]
1. I'm ok with switching since we picked django-tables2 thinking it would be easier, but if it's not, no point in using it. I admit I don't entirely understand how using tablesorter resolves the two issues you presented, but I trust you and don't need to fully understand it.
2. I agree with using Bootstrap theme, the UX is good (and tested!).
3. We won't be able to sort by Cohorts at all because with students in multiple cohorts (many are) there's no obvious way to sort. Let's disable Cohort field sorting please.

**Comment by jonespm** [comment]
Well up to @zqian Zhen on what she'd like to use. I put in a PR for table sorter and created #110 to capture the status column that we'd need to sort separately. I think it looks good and this solution here also solves #102

**Comment by mfldavidson** [comment]
It only solves #102 filtering by columns other than status, but status filtering is the most important. I feel like the UX for filtering by cohort would also be better if we showed them each cohort they have and let them check or uncheck cohorts instead of making them know the name and start typing it. This was one of the reasons I had no particular attachment to using table sorter, because I felt the filtering functionality was not what we needed. I'm happy to use it for name and UMID filtering, I think that works great. But not so sure about the other two.

**Comment by jonespm** [comment]
I think this will work like you like, I'll can demo it tomorrow if you're around. I might have a conflict for the meeting next Tuesday.
