### ISSUE TITLE
Improve load speed by investigating duplicate and similar queries

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#136]
Load speed is currently very slow. Debug toolbar in test shows some duplicate and some similar SQL queries that we can investigate to improve efficiency.

Look at:
- advisor's view of their own cohort /advisors/<advisor uniqname>/ (AdvisorView)
- individual student /students/<student uniqname>/ (StudentView)
- individual course /students/<student uniqname>/class_sites/<canvas course ID>/ (ClassSiteView)
[Views referenced are in seumich/views.py](https://github.com/tl-its-umich-edu/student_explorer/blob/develop/seumich/views.py)

Acceptance criteria: investigate all duplicate and similar SQL queries and remove/combine any that we can without negatively affecting functionality

**Comment by jonespm** [comment]
Some guides
https://realpython.com/caching-in-django-with-redis/
https://code.tutsplus.com/tutorials/how-to-cache-using-redis-in-django-applications--cms-30178

**Comment by ssciolla** [comment]
@jonespm, I just took a close look at `AdvisorView`, since we've been working on that one already. Currently we're using `prefetch_related`. 

https://github.com/tl-its-umich-edu/student_explorer/blob/0049c25abe106c1eb1d0ed06cdf4a3ee950ef8e9/seumich/views.py#L112

Looking at the relevant [Django documentation](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#prefetch-related), I believe this is causing the extra queries. The alternative `select_related` -- which uses extra joins to create larger queries, helping performance -- seems to only work in simple 1:M and 1:1 relationships. Unfortunately, the data used (cohorts, classes, or class status) all seem to be accessed through M:M relationships. I will review some of the other views today to see if the situation is different.
