### ISSUE TITLE
Accessing Advisor page for someone who is not a user throws an error

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student_explorer#165]
I think there's a bug here on line 98 that's causing an error if the user is not a mentor. It probably should be `username=kwargs['advisor']` not `username=self.kwargs['advisor'] `

I'll see if I can find a local test case but it's easy to reproduce on the test server. 

https://github.com/tl-its-umich-edu/student_explorer/blob/0049c25abe106c1eb1d0ed06cdf4a3ee950ef8e9/seumich/views.py#L98

**Comment by ssciolla** [comment]
The error seems to be thrown in cases where the advisor has an associated `Mentor` object (they are in `DM_MNTR') but is not a `User` yet in the application. We should be able to fix this by changing the `get_context_data` method on `AdvisorView` so that the `user` assignment is under the `else` clause, like so:

```
   def get_context_data(self, **kwargs):
        context = super(AdvisorView, self).get_context_data(**kwargs)
        if self.mentor is not None:
            context['studentListHeader'] = " ".join([self.mentor.first_name, self.mentor.last_name])
            context['advisor'] = self.mentor
        else:
            user = get_user_model().objects.get(username=self.kwargs['advisor'])
            context['studentListHeader'] = " ".join([user.first_name, user.last_name])
            context['advisor'] = user
        return context
```

I will try this and write a new test (or two) soon.
