### ISSUE TITLE
Support configurable EMAIL_SUBJECT_PREFIX

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student_explorer#190]
We should have an environment variable where we can set [EMAIL_SUBJECT_PREFIX](https://docs.djangoproject.com/en/1.11/ref/settings/#email-subject-prefix)

The default is  `[Django]`

I'd want to set this to something like `[NON-PROD Student Explorer]` for the test instance or just `Student Explorer` for production. Then we can just re-use the same monitoring email address for both messages.

**Comment by jonespm** [comment]
This should be an easy fix, what do you think @ssciolla and @mfldavidson ?

I noticed that the previous dev instance only sent errors to me, while prod sent errors to student-explorer-monitoring. However the subject line made it somewhat hard to tell where these were coming from. This issue today made this more of an issue.

**Comment by mfldavidson** [comment]
Yes I think this is important to fix. We've gotten errors from test that are hard to tell apart from prod and really freaked me and Zhen out.

**Comment by anantakash73** [comment]
Hi, can I take a crack at this? 
Any pointers on where I should get started.

**Comment by jonespm** [comment]
Hi! Yes, this issue should be pretty straightforward.

If you're able to get the software running in Docker as described in the README (Only currently tested on OSX and Linux) you should be able to login to the user interface.

We just need to add a new value to the settings.py for EMAIL_SUBJECT_PREFIX here to pull it that setting out of the settings. This might only be a one line change. 

Email Subject Prefix is a setting from Django:
https://docs.djangoproject.com/en/1.11/ref/settings/#email-subject-prefix

If this was changed any emails wouldn't say just '[Django] ' but whatever we define. 

A nice change semi-related to this would be #119 to switch over the configuration to something outside of settings if you needed something larger to work on.

**Comment by anantakash73** [comment]
I was able to run it on Docker locally, although I am unsure on how to trigger the actual email sending process to test if the env change has worked. 

I'll also take a look at [119](https://github.com/tl-its-umich-edu/student_explorer/issues/119)

**Comment by anantakash73** [comment]
Pull request created [here](https://github.com/tl-its-umich-edu/student_explorer/pull/193)

**Comment by jonespm** [comment]
I believe this was typically triggered when you have DJANGO_DEBUG=true and you might have to define DJANGO_ERROR_EMAIL. 

By default DJANGO_EMAIL_HOST=localhost and DJANGO_EMAIL_POST=25 so you'd have to also be running an email server there.

Python has a good way to debug this locally by setting up an [SMTP server. ](https://realpython.com/python-send-email/#option-2-setting-up-a-local-smtp-server
)

However the trick would be that you'd have to run this inside the Docker instance. You'd either have have a new docker-compose entry to have this SMTP container that listens, or you'd have to login to the web and start this job up. I think it's available. 

`docker exec -it student_explorer /bin/bash`
Then
`python -m smtpd -c DebuggingServer -n localhost:25`

Give that a try!

**Comment by jonespm** [comment]
So then after you had that all setup you'd have to get the server to generate an error. I think just going to an invalid URL would generate this message.

**Comment by anantakash73** [comment]
![image](https://user-images.githubusercontent.com/8619489/70110937-addd1a80-161e-11ea-9bae-85781730a3f9.png)

Took me a while to figure out a good way to test this. Turns out Django only sends error emails under certain conditions as indicated [here](https://docs.djangoproject.com/en/2.2/howto/error-reporting/)

I could not trigger an email for an error but I was able to trigger one for feedback and see it's output using the local smtpd server. 
So, I went into the method that handled feedback submission and changed it to **mail_admin** from **send_email**. This was done because the EMAIL_SUBJECT_PREFIX only works on emails sent to ADMINS as set in settings. After doing so, the required EMAIL_SUBJECT_PREFIX of 'Student Explorer ' showed up. I will posit that this means that when actual server error emails are sent, the prefix will be added. 

Please let me know if additional testing is required for this PR.

**Comment by jonespm** [comment]
Yeah that sounds like what we'd want, thanks for testing it!

**Comment by mfldavidson** [comment]
This is done right? Ok to close? @jonespm
