### ISSUE TITLE
Update SE to Django 2.2

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#198]

**Comment by ssciolla** [comment]
I've started work on this, and you check my progress on my [issue-198-update-django branch](https://github.com/tl-its-umich-edu/student_explorer/compare/develop...ssciolla:issue-198-update-django). Things are working locally right now, but I still need to do more testing. I will aim to have a version we can build in OpenShift soon so that others can help with testing.

Here's an ongoing task list:

- [x] Update `Dockerfile` to use Python 3.7 as a base image.
- [x] Update Django and other dependencies (where possible) in `requirements.txt`.
- [ ] Evaluate and consider replacing or removing outdated dependencies.
- [x] Add `on_delete=models.CASCADE` to `*/models.py` and migration files as necessary.
- [x] Update `urlpatterns` to use `path()` (instead of `url()`)
- [x] Fix `urls.py` for non-`student_explorer` apps by adding `app_name` variables.
- [x] Remove `SessionAuthenticationMiddleware`.
- [x] Change use of `user.is_authenticated()` to `user.is_authenticated`.
- [x] Get `seumich/tests.py` to run successfully by specifying databases in `SeumichTest`.
- [ ] Test all routes.
- [ ] Test SAML.
- [ ] Test cohort creation.
- [ ] Test management commands.
- [ ] Test feedback form.

**Comment by mfldavidson** [comment]
Some specific things I've tested or will test that are not covered in Sam's list above that I want to track:
- [x] Test all links from the About page
- [ ] Test all links from the advisor with no students route
- [x] Test all links in the header and footer
- [x] Test search - three different strings ["jmaggie","john","001"]
