### ISSUE TITLE
show UDW schemaversion and canvasdatadate in Student Explorer footer

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/student_explorer#38]
This is a followup issue with [issue_15](https://github.com/tl-its-umich-edu/student_explorer/issues/15):

IQ team has updated the SE ETL process to include the UDW data refresh date and schema version into CNLYR002.LRNG_ANLTCS_STAT:

select DW_DATA_NM, EXTRCT_DT, LOAD_DT, DW_OWNR_NM
FROM CNLYR002.LRNG_ANLTCS_STAT;

Student Explorer Daily Tables	2019-01-24 23:39:59	2019-01-25 00:13:03	cnlyr002
LARC Data Set	2018-09-25 07:00:14	2018-09-25 07:31:56	cnlyr002
Student Explorer Weekly Tables	2019-01-20 15:07:31	2019-01-20 17:54:30	cnlyr002
UDW Daily Tables	2019-01-24 00:00:00	2019-01-24 00:00:00	4.2.1

**Comment by zqian** [comment]
[issue_15](https://github.com/tl-its-umich-edu/student_explorer/issues/15)

**Comment by zqian** [comment]
@mfldavidson Please test it on [Dev Server](https://dev.studentexplorer.openshift.dsc.umich.edu)

**Comment by mfldavidson** [comment]
This is what I'm seeing right now: 
![image](https://user-images.githubusercontent.com/31591389/52374474-62bca000-2a2b-11e9-8cb6-b83538924131.png) I think that if the time is always going to be 0 we would ideally cut off the T and everything after. It looks messy and there's no need for it. Also I'm wondering if we can clarify what "UDW Last Updated on" means because I think users would be very confused by that. If not possible, I can put information in the documentation. Thank you.

**Comment by mfldavidson** [comment]
Recommended language and format:
"Data last updated from Canvas yyyy-mm-dd hh:mm AM EST
(UDW yyyy-mm-ddThh:mm:ss+00:00; Schema: n.n.n)" where the top row is intended for end users to understand but the bottom row still gives us what we need to know. I'm wondering if it is possible and not too cumbersome to translate UTC into EST for the top row?

**Comment by jonespm** [comment]
Right, dev right now doesn't look good. 

I don't think we need two dates conveying the same information with just the time zone shifted. I'm fine with just having it be 

"Data last updated from Canvas yyyy-mm-dd hh:mm AM EST | Schema: n.n.n"

The second UDW row doesn't seem to add anything for me.

**Comment by jonespm** [comment]
I made a update that just has
![image](https://user-images.githubusercontent.com/27447/52646749-53b57200-2eb1-11e9-86e1-c2fbe46d9df4.png)

This is an alternate format that has both but doesn't seem as readable
![image](https://user-images.githubusercontent.com/27447/52646838-8495a700-2eb1-11e9-8461-643dde16b66b.png)

**Comment by zqian** [comment]
@mfldavidson please test this on dev server

**Comment by mfldavidson** [comment]
@zqian @jonespm IMO this is perfect. I only suggested the two options because I wasn't clear on what the reason behind the request was and thought it was mostly for developers who might need all that additional information. I think so long as what is there now provides what the original requestor wanted (who was that?) I am happy with it. Thank you.

**Comment by jonespm** [comment]
Nope, developers are happy. If developers needed more info it should be off on a separate page anyway away from users.
