### ISSUE TITLE
More info link on about page is broken, about page maybe isn't necessary

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student_explorer#85]
If you click the version number in the footer you go to the about page.

/about

This page is a broken link. I either think this link should be removed or replaced with a working link. We also just might want to remove the link from the version in the footer to this page since we have the nice "resources and support" page now and it seems like this page is mostly administrative.

**Comment by mfldavidson** [comment]
I have been thinking about doing something with this "About" page. Agree that the version number should not link here but it doesn't look like a link so I doubt many people are clicking it. It has only had 8 pageviews since 9/1/18 and I'm pretty sure most, if not all, of those are us. I would categorize this as very low priority, but you're welcome to either unlink it or change the link on the About page ("more info") to link to the ITS documentation instead of the broken AI link

**Comment by jonespm** [comment]
Closing this as it seems duplicated by #86
